global.stageName[0] = "[0] Kill The Kamilia"; global.stageRoom[0] = rStage0;
global.stageName[1] = "[1-1] ChockoChocko"; global.stageRoom[1] = rStage1Chocko;
global.stageName[2] = "[1-2] GGM"; global.stageRoom[2] = rStage1GGM;
global.stageName[3] = "Stage 1 Enjoy The Game"; global.stageRoom[3] = rStage1EnjoyTheGame;
global.stageName[4] = "Stage 1 Conquer The Blow Game"; global.stageRoom[4] = rStage1CTB1;
global.stageName[5] = "Stage 1 Mysterious House"; global.stageRoom[5] = rStage1MysHouse;
global.stageName[6] = "Stage 1 Yellow Star"; global.stageRoom[6] = rStage1YellowStar;
global.stageName[7] = "Stage 1 Dark Blue"; global.stageRoom[7] = rStage1DarkBlue;
global.stageName[8] = "Stage 1 Experience"; global.stageRoom[8] = rStage1Exp;
global.stageName[9] = "Stage 1 Fortress Returns"; global.stageRoom[9] = rStage1Fortress;
global.stageName[10] = "Stage 1 Fangame"; global.stageRoom[10] = rStage1Fangame;
global.stageName[11] = "Boss 1 Volcano Zone"; global.stageRoom[11] = rBoss1Save;
global.stageName[12] = "Stage 2 Conquer The Blow Game 2"; global.stageRoom[12] = rStage2CTB2;
global.stageName[13] = "Stage 2 Graduate From DT"; global.stageRoom[13] = rStage2DT;
global.stageName[14] = "Stage 2 Green Moon"; global.stageRoom[14] = rStage2GreenMoon;
global.stageName[15] = "Stage 2 Showdown"; global.stageRoom[15] = rStage2Showdown;
global.stageName[16] = "Stage 2 Greeeen"; global.stageRoom[16] = rStage2Green;
global.stageName[17] = "Stage 2 Tribute"; global.stageRoom[17] = rStage2Tribute;
global.stageName[18] = "Stage 2 Yassan"; global.stageRoom[18] = rStage2Yassan;
global.stageName[19] = "Stage 2 Run The Terminal"; global.stageRoom[19] = rStage2RunTerminal;
global.stageName[20] = "Stage 2 Best Guy"; global.stageRoom[20] = rStage2BestGuy;
global.stageName[21] = "Stage 2 IWBTG"; global.stageRoom[21] = rStage2GuyTower;
global.stageName[22] = "Stage 2 Miku"; global.stageRoom[22] = rStage2GuyTower2;
global.stageName[23] = "Boss 2 Guy's Castle"; global.stageRoom[23] = rBoss2Save;
global.stageName[24] = "Stage 3 500"; global.stageRoom[24] = rStage3500;
global.stageName[25] = "Stage 3 Uhuhu Spike"; global.stageRoom[25] = rStage3Uhuhu;
global.stageName[26] = "Stage 3 Skyclad"; global.stageRoom[26] = rStage3Skyclad;
global.stageName[27] = "Stage 3 CQ"; global.stageRoom[27] = rStage3CQ;
global.stageName[28] = "Stage 3 Rukimin"; global.stageRoom[28] = rStage3Rukimin;
global.stageName[29] = "Stage 3 Diverse"; global.stageRoom[29] = rStage3Diverse;
global.stageName[30] = "Stage 3 Heaven Trap 2"; global.stageRoom[30] = rStage3HeavenTrap;
global.stageName[31] = "Stage 3 See The Moon"; global.stageRoom[31] = rStage3SeeTheMoon;
global.stageName[32] = "Stage 3 White Cherry"; global.stageRoom[32] = rStage3WhiteCherry;
global.stageName[33] = "Stage 3 Take The Time-machine"; global.stageRoom[33] = rStage3TimeMachine;
global.stageName[34] = "Boss 3 Influka Room"; global.stageRoom[34] = rBoss3Save;
global.stageName[35] = "Stage 4 Galaxy"; global.stageRoom[35] = rStage4Galaxy;
global.stageName[36] = "Stage 4 GB"; global.stageRoom[36] = rStage4GB;
global.stageName[37] = "Stage 4 Phantom"; global.stageRoom[37] = rStage4Phantom;
global.stageName[38] = "Stage 4 Device"; global.stageRoom[38] = rStage4Device;
global.stageName[39] = "Stage 4 Heaven Trap"; global.stageRoom[39] = rStage4HeavenTrap;
global.stageName[40] = "Stage 4 Shiny Spark"; global.stageRoom[40] = rStage4ShinySparkA;
global.stageName[41] = "Stage 4 Conscience"; global.stageRoom[41] = rStage4Conscience;
global.stageName[42] = "Stage 4 Explorer"; global.stageRoom[42] = rStage4Explorer;
global.stageName[43] = "Stage 4 Competitor"; global.stageRoom[43] = rStage4Competitor;
global.stageName[44] = "Stage 4 Kill The Guy"; global.stageRoom[44] = rStage4KTGA;
global.stageName[45] = "Stage 4 Ghost town"; global.stageRoom[45] = rStage4KTGB;
global.stageName[46] = "Boss 4 Geezer Room"; global.stageRoom[46] = rBoss4Save;
global.stageName[47] = "Stage 5 Color"; global.stageRoom[47] = rStage5Color;
global.stageName[48] = "Stage 5 Scapegoat"; global.stageRoom[48] = rStage5Scapegoat;
global.stageName[49] = "Stage 5 Symmetry"; global.stageRoom[49] = rStage5Symetry;
global.stageName[50] = "Stage 5 Rainbow Miku"; global.stageRoom[50] = rStage5RainbowMiku;
global.stageName[51] = "Stage 5 Unknown"; global.stageRoom[51] = rStage5Unknown;
global.stageName[52] = "Stage 5 Blood Festival"; global.stageRoom[52] = rStage5BloodFestival;
global.stageName[53] = "Stage 5 Dieary"; global.stageRoom[53] = rStage5Dieary;
global.stageName[54] = "Stage 5 PYF"; global.stageRoom[54] = rStage5PYF;
global.stageName[55] = "Stage 5 Locus"; global.stageRoom[55] = rStage5Locus;
global.stageName[56] = "Stage 5 Boshy"; global.stageRoom[56] = rStage5Boshy;
global.stageName[57] = "Boss 5 Solgryn Room"; global.stageRoom[57] = rBoss5Save;
global.stageName[58] = "Stage 6 GR"; global.stageRoom[58] = rStage6GR;
global.stageName[59] = "Stage 6 Dot Kid"; global.stageRoom[59] = rStage6DotKid;
global.stageName[60] = "Stage 6 Seven Trials"; global.stageRoom[60] = rStage6SevenTrials;
global.stageName[61] = "Stage 6 Sadist"; global.stageRoom[61] = rStage6Sadist;
global.stageName[62] = "Stage 6 Catastrophe"; global.stageRoom[62] = rStage6Catastrophe;
global.stageName[63] = "Stage 6 Crimson"; global.stageRoom[63] = rStage6Crimson;
global.stageName[64] = "Stage 6 Destination"; global.stageRoom[64] = rStage6Destination;
global.stageName[65] = "Stage 6 Breaking Out"; global.stageRoom[65] = rStage6BreakingOut;
global.stageName[66] = "Stage 6 Popularity"; global.stageRoom[66] = rStage6Popularity;
global.stageName[67] = "Stage 6 Love Trap"; global.stageRoom[67] = rStage6LoveTrap;
global.stageName[68] = "Boss 6 Big Kid"; global.stageRoom[68] = rBoss6Phase1;
