global.stageName[0] = "[0] Kill The Kamilia"; global.stageRoom[0] = rStage0;
global.stageName[1] = "[1-1] ChockoChocko"; global.stageRoom[1] = rStage1Chocko;
global.stageName[2] = "[1-2] GGM"; global.stageRoom[2] = rStage1GGM;
global.stageName[3] = "[1-3] Enjoy The Game"; global.stageRoom[3] = rStage1EnjoyTheGame;
global.stageName[4] = "[1-4] Conquer The Blow Game"; global.stageRoom[4] = rStage1CTB1;
global.stageName[5] = "[1-5] Mysterious House"; global.stageRoom[5] = rStage1MysHouse;
global.stageName[6] = "[1-6] Yellow Star"; global.stageRoom[6] = rStage1YellowStar;
global.stageName[7] = "[1-7] Dark Blue"; global.stageRoom[7] = rStage1DarkBlue;
global.stageName[8] = "[1-8] Experience"; global.stageRoom[8] = rStage1Exp;
global.stageName[9] = "[1-9] Fortress Returns"; global.stageRoom[9] = rStage1Fortress;
global.stageName[10] = "[1-10] Fangame"; global.stageRoom[10] = rStage1Fangame;
global.stageName[11] = "[1-B] Volcano Zone"; global.stageRoom[11] = rBoss1Save;
global.stageName[12] = "[2-1] Conquer The Blow Game 2"; global.stageRoom[12] = rStage2CTB2;
global.stageName[13] = "[2-2] Graduate From DT"; global.stageRoom[13] = rStage2DT;
global.stageName[14] = "[2-3] Green Moon"; global.stageRoom[14] = rStage2GreenMoon;
global.stageName[15] = "[2-4] Showdown"; global.stageRoom[15] = rStage2Showdown;
global.stageName[16] = "[2-5] Greeeen"; global.stageRoom[16] = rStage2Green;
global.stageName[17] = "[2-6] Tribute"; global.stageRoom[17] = rStage2Tribute;
global.stageName[18] = "[2-7] Yassan"; global.stageRoom[18] = rStage2Yassan;
global.stageName[19] = "[2-8] Run The Terminal"; global.stageRoom[19] = rStage2RunTerminal;
global.stageName[20] = "[2-9] Best Guy"; global.stageRoom[20] = rStage2BestGuy;
global.stageName[21] = "[2-10] IWBTG"; global.stageRoom[21] = rStage2GuyTower;
global.stageName[22] = "[2-B1] Miku"; global.stageRoom[22] = rStage2GuyTower2;
global.stageName[23] = "[2-B2] Guy's Castle"; global.stageRoom[23] = rBoss2Save;
global.stageName[24] = "[3-1] 500"; global.stageRoom[24] = rStage3500;
global.stageName[25] = "[3-2] Uhuhu Spike"; global.stageRoom[25] = rStage3Uhuhu;
global.stageName[26] = "[3-3] Skyclad"; global.stageRoom[26] = rStage3Skyclad;
global.stageName[27] = "[3-4] CQ"; global.stageRoom[27] = rStage3CQ;
global.stageName[28] = "[3-5] Rukimin"; global.stageRoom[28] = rStage3Rukimin;
global.stageName[29] = "[3-6] Diverse"; global.stageRoom[29] = rStage3Diverse;
global.stageName[30] = "[3-7] HeavenTrap 2"; global.stageRoom[30] = rStage3HeavenTrap;
global.stageName[31] = "[3-8] See The Moon"; global.stageRoom[31] = rStage3SeeTheMoon;
global.stageName[32] = "[3-9] White Cherry"; global.stageRoom[32] = rStage3WhiteCherry;
global.stageName[33] = "[3-10] Take The Time-machine"; global.stageRoom[33] = rStage3TimeMachine;
global.stageName[34] = "[3-B] Influka Room"; global.stageRoom[34] = rBoss3Save;
global.stageName[35] = "[4-1] Galaxy"; global.stageRoom[35] = rStage4Galaxy;
global.stageName[36] = "[4-2] GB"; global.stageRoom[36] = rStage4GB;
global.stageName[37] = "[4-3] Phantom"; global.stageRoom[37] = rStage4Phantom;
global.stageName[38] = "[4-4] Device"; global.stageRoom[38] = rStage4Device;
global.stageName[39] = "[4-5] HeavenTrap"; global.stageRoom[39] = rStage4HeavenTrap;
global.stageName[40] = "[4-6] Shiny Spark"; global.stageRoom[40] = rStage4ShinySparkA;
global.stageName[41] = "[4-7] Conscience"; global.stageRoom[41] = rStage4Conscience;
global.stageName[42] = "[4-8] Explorer"; global.stageRoom[42] = rStage4Explorer;
global.stageName[43] = "[4-9] Competitor"; global.stageRoom[43] = rStage4Competitor;
global.stageName[44] = "[4-10] Kill The Guy"; global.stageRoom[44] = rStage4KTGA;
global.stageName[45] = "[4-11] Ghost town"; global.stageRoom[45] = rStage4KTGB;
global.stageName[46] = "[4-B] Geezer Room"; global.stageRoom[46] = rBoss4Save;
global.stageName[47] = "[5-1] Color"; global.stageRoom[47] = rStage5Color;
global.stageName[48] = "[5-2] Scapegoat"; global.stageRoom[48] = rStage5Scapegoat;
global.stageName[49] = "[5-3] Symmetry"; global.stageRoom[49] = rStage5Symetry;
global.stageName[50] = "[5-4] Rainbow Miku"; global.stageRoom[50] = rStage5RainbowMiku;
global.stageName[51] = "[5-5] Unknown"; global.stageRoom[51] = rStage5Unknown;
global.stageName[52] = "[5-6] Blood Festival"; global.stageRoom[52] = rStage5BloodFestival;
global.stageName[53] = "[5-7] Dieary"; global.stageRoom[53] = rStage5Dieary;
global.stageName[54] = "[5-8] PYF"; global.stageRoom[54] = rStage5PYF;
global.stageName[55] = "[5-9] Locus"; global.stageRoom[55] = rStage5Locus;
global.stageName[56] = "[5-10] Boshy"; global.stageRoom[56] = rStage5Boshy;
global.stageName[57] = "[5-B] Solgryn Room"; global.stageRoom[57] = rBoss5Save;
global.stageName[58] = "[5-B2] Solgryn phase 2"; global.stageRoom[58] = rBoss5Phase2;
global.stageName[59] = "[6-1] GR"; global.stageRoom[59] = rStage6GR;
global.stageName[60] = "[6-2] Dot Kid"; global.stageRoom[60] = rStage6DotKid;
global.stageName[61] = "[6-3] Seven Trials"; global.stageRoom[61] = rStage6SevenTrials;
global.stageName[62] = "[6-4] Sadist"; global.stageRoom[62] = rStage6Sadist;
global.stageName[63] = "[6-5] Catastrophe"; global.stageRoom[63] = rStage6Catastrophe;
global.stageName[64] = "[6-6] Crimson"; global.stageRoom[64] = rStage6Crimson;
global.stageName[65] = "[6-7] Destination"; global.stageRoom[65] = rStage6Destination;
global.stageName[66] = "[6-8] Breaking Out"; global.stageRoom[66] = rStage6BreakingOut;
global.stageName[67] = "[6-9] Popularity"; global.stageRoom[67] = rStage6Popularity;
global.stageName[68] = "[6-10] LoveTrap"; global.stageRoom[68] = rStage6LoveTrap;
global.stageName[69] = "[6-B] Big Kid"; global.stageRoom[69] = rBoss6Phase1;
global.stageName[70] = "[6-B2] The Chase"; global.stageRoom[70] = rBoss6Phase2;
global.stageName[71] = "[7-1] M-Stage 1"; global.stageRoom[71] = rBoss6Death;
global.stageName[72] = "[7-2] M-Stage 2"; global.stageRoom[72] = rStage7;
global.stageName[73] = "[7-B] Kamilia"; global.stageRoom[73] = rStage7B;
global.stageName[74] = "[7-B2] Kamilia phase 2"; global.stageRoom[74] = rBoss7Phase2;
global.stageName[75] = "[7-B3] Kamilia phase 4"; global.stageRoom[75] = rBoss7Phase4Pre;
global.stageName[76] = "WARP TO HOME"; global.stageRoom[76] = rHomeBad;
global.stageName[77] = "Extra stage"; global.stageRoom[77] = rExtraStageMaze;
global.stageName[78] = "Ex BOSHY Boss"; global.stageRoom[78] = rExtraStageBoshy;
global.stageName[79] = "Ex KTG Boss"; global.stageRoom[79] = rExtraStageKTGSray;
global.stageName[80] = "Ex Destination boss"; global.stageRoom[80] = rExtraStageDestinationBananas;
global.stageName[81] = "Ex Blood Festival Boss"; global.stageRoom[81] = rExtraStageBloodFestivalBoss;
global.stageName[82] = "The Hands of Time"; global.stageRoom[82] = rExtraStageFinalDeadRoom;
global.stageName[83] = "Shutdown";
global.stageName[84] = "Bottomless abyss"; global.stageRoom[84] = rRedLunarAbyss;
global.stageName[85] = "Ending"; global.stageRoom[85] = rTrueEnding;
